### ISSUE TITLE
introduce into ueberdb

### ISSUE THREAD

**Issue by JohnMcLear** [pubkey/event-reduce#3]
Seems that ueberdb could leverage this really well.  It'd be cool to bring it in.  Https://GitHub.com/ether/ueberdb

**Comment by pubkey** [comment]
I'm closing this. I think you should open this issue in the ueberdb repo since the work must also be done there.

**Comment by JohnMcLear** [comment]
FWIW peep the dirtyref branch I just in metrics and database checks so it would be really cool to see a before & after w/ event-reduce and I think ueber is a perfect project for you to demostrate with because you would get so much datababies supported from the get go!

**Comment by pubkey** [comment]
Yes but if you imply that I should do this, then sorry I don't have the time for it.
Also ueberdb does not abstract the change-stream which makes it difficult to add event-reduce for each of these databases.

**Comment by JohnMcLear** [comment]
Ack, okay never mind then :)
